on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: [ master ]
name: create-pull-request workflow
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-R@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("dplyr", "ggplot2", "RcppRoll", "lubridate", "extrafont", "paletteer"))
        shell: Rscript {0} 
        
      - name: Generate data & plots
        run: |
          source("R/job.R")
          source("R/regularDashboardRun.R")
          source("R/colinsPlots.R")
        shell: Rscript {0} 
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Recreated plots etc
          title: '[Example] Recreating plots'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: report, automated pr
